name: core
description: "Tools and utilities"
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  design_system:
    path: ../design_system
  flutter_modular: ^6.3.4
  flutter_localizations:
    sdk: flutter
  intl: any
  medartor: ^1.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  assets: